### ISSUE TITLE
Lenovo 2010-a keyboard Crash on Use

### ISSUE THREAD

**Issue by gprakhar** [klausw/hackerskeyboard#492]
hi,

Lenovo A2010-a 
android 5.1

On activating and using Keyboard, it stops working with error msg,
"Unfortunately, hacker's keyboard has stopped"

How to obtain debugging information ?
Please let know if more information is required.

**Comment by hyperpostulate** [comment]
Same issue on Lenovo P70/A. Logcat output when crash is,

"03-10 18:40:07.479 6738-6738/org.pocketworkstation.pckeyboard E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: org.pocketworkstation.pckeyboard, PID: 6738
                                                                                java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
                                                                                    at android.widget.TextView.checkForRelayout(TextView.java:7129)
                                                                                    at android.widget.TextView.onRtlPropertiesChanged(TextView.java:9296)
                                                                                    at android.view.View.resolvePadding(View.java:13547)
                                                                                    at android.view.View.resolveRtlPropertiesIfNeeded(View.java:13298)
                                                                                    at android.view.View.setLayoutDirection(View.java:6967)
                                                                                    at android.widget.PopupWindow.setLayoutDirectionFromAnchor(PopupWindow.java:1131)
                                                                                    at android.widget.PopupWindow.invokePopup(PopupWindow.java:1114)
                                                                                    at android.widget.PopupWindow.showAtLocation(PopupWindow.java:944)
                                                                                    at android.widget.PopupWindow.showAtLocation(PopupWindow.java:908)
                                                                                    at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.showKey(LatinKeyboardBaseView.java:1265)
                                                                                    at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.access$000(LatinKeyboardBaseView.java:81)
                                                                                    at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView$UIHandler.handleMessage(LatinKeyboardBaseView.java:294)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5627)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)"

There is also another error before crash.  

"03-10 18:40:04.149 6738-6738/org.pocketworkstation.pckeyboard E/BinaryDictionary: Could not load native library jni_pckeyboard
03-10 18:40:04.150 6738-6738/org.pocketworkstation.pckeyboard E/art: No implementation found for long org.pocketworkstation.pckeyboard.BinaryDictionary.openNative(java.nio.ByteBuffer, int, int, int) (tried Java_org_pocketworkstation_pckeyboard_BinaryDictionary_openNative and Java_org_pocketworkstation_pckeyboard_BinaryDictionary_openNative__Ljava_nio_ByteBuffer_2III)
03-10 18:40:04.150 6738-6738/org.pocketworkstation.pckeyboard W/BinaryDictionary: Failed to load native dictionary
                                                                                  java.lang.UnsatisfiedLinkError: No implementation found for long org.pocketworkstation.pckeyboard.BinaryDictionary.openNative(java.nio.ByteBuffer, int, int, int) (tried Java_org_pocketworkstation_pckeyboard_BinaryDictionary_openNative and Java_org_pocketworkstation_pckeyboard_BinaryDictionary_openNative__Ljava_nio_ByteBuffer_2III)
                                                                                      at org.pocketworkstation.pckeyboard.BinaryDictionary.openNative(Native Method)
                                                                                      at org.pocketworkstation.pckeyboard.BinaryDictionary.loadDictionary(BinaryDictionary.java:145)
                                                                                      at org.pocketworkstation.pckeyboard.BinaryDictionary.loadDictionary(BinaryDictionary.java:173)
                                                                                      at org.pocketworkstation.pckeyboard.BinaryDictionary.<init>(BinaryDictionary.java:78)
                                                                                      at org.pocketworkstation.pckeyboard.Suggest.<init>(Suggest.java:109)
                                                                                      at org.pocketworkstation.pckeyboard.LatinIME.initSuggest(LatinIME.java:585)
                                                                                      at org.pocketworkstation.pckeyboard.LatinIME.onCreate(LatinIME.java:440)
                                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2981)
                                                                                      at android.app.ActivityThread.access$1800(ActivityThread.java:177)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                      at android.os.Looper.loop(Looper.java:194)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5627)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)"

I gathered this info via clone project from github, and run on my phone. [Using Android Studio 1.5.1, project built with API level 22]

**Comment by atakancoban** [comment]
Same issue on Lenovo P70/A. Logcat output when crash is,

"03-10 18:40:07.479 6738-6738/org.pocketworkstation.pckeyboard E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.pocketworkstation.pckeyboard, PID: 6738
java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
at android.widget.TextView.checkForRelayout(TextView.java:7129)
at android.widget.TextView.onRtlPropertiesChanged(TextView.java:9296)
at android.view.View.resolvePadding(View.java:13547)
at android.view.View.resolveRtlPropertiesIfNeeded(View.java:13298)
at android.view.View.setLayoutDirection(View.java:6967)
at android.widget.PopupWindow.setLayoutDirectionFromAnchor(PopupWindow.java:1131)
at android.widget.PopupWindow.invokePopup(PopupWindow.java:1114)
at android.widget.PopupWindow.showAtLocation(PopupWindow.java:944)
at android.widget.PopupWindow.showAtLocation(PopupWindow.java:908)
at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.showKey(LatinKeyboardBaseView.java:1265)
at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.access$000(LatinKeyboardBaseView.java:81)
at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView$UIHandler.handleMessage(LatinKeyboardBaseView.java:294)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5627)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)"

There is also another error before crash.

"03-10 18:40:04.149 6738-6738/org.pocketworkstation.pckeyboard E/BinaryDictionary: Could not load native library jni_pckeyboard
03-10 18:40:04.150 6738-6738/org.pocketworkstation.pckeyboard E/art: No implementation found for long org.pocketworkstation.pckeyboard.BinaryDictionary.openNative(java.nio.ByteBuffer, int, int, int) (tried Java_org_pocketworkstation_pckeyboard_BinaryDictionary_openNative and Java_org_pocketworkstation_pckeyboard_BinaryDictionary_openNative__Ljava_nio_ByteBuffer_2III)
03-10 18:40:04.150 6738-6738/org.pocketworkstation.pckeyboard W/BinaryDictionary: Failed to load native dictionary
java.lang.UnsatisfiedLinkError: No implementation found for long org.pocketworkstation.pckeyboard.BinaryDictionary.openNative(java.nio.ByteBuffer, int, int, int) (tried Java_org_pocketworkstation_pckeyboard_BinaryDictionary_openNative and Java_org_pocketworkstation_pckeyboard_BinaryDictionary_openNative__Ljava_nio_ByteBuffer_2III)
at org.pocketworkstation.pckeyboard.BinaryDictionary.openNative(Native Method)
at org.pocketworkstation.pckeyboard.BinaryDictionary.loadDictionary(BinaryDictionary.java:145)
at org.pocketworkstation.pckeyboard.BinaryDictionary.loadDictionary(BinaryDictionary.java:173)
at org.pocketworkstation.pckeyboard.BinaryDictionary.(BinaryDictionary.java:78)
at org.pocketworkstation.pckeyboard.Suggest.(Suggest.java:109)
at org.pocketworkstation.pckeyboard.LatinIME.initSuggest(LatinIME.java:585)
at org.pocketworkstation.pckeyboard.LatinIME.onCreate(LatinIME.java:440)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2981)
at android.app.ActivityThread.access$1800(ActivityThread.java:177)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5627)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)"

I gathered this info via clone project from github, and run on my phone. [Using Android Studio 1.5.1, project built with API level 22]

**Comment by w201024** [comment]
Same issue on Lenovo P70/A.
On activating and using Keyboard, it stops working with error msg,
"Unfortunately, hacker's keyboard has stopped"
