### ISSUE TITLE
Crash on LineageOS 18 (Android 11)

### ISSUE THREAD

**Issue by sphinkx** [klausw/hackerskeyboard#864]
After install i tried to setup additional languages, looks like crash happened on save settings
```
FATAL EXCEPTION: AsyncTask #2
Process: org.pocketworkstation.pckeyboard, PID: 17687
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/mnt/expand/322a2c56-97f5-4a06-a139-ba607a4eb84d/user/0/org.pocketworkstation.pckeyboard/databases/auto_dict.db': Directory /mnt/expand/322a2c56-97f5-4a06-a139-ba607a4eb84d/user/0/org.pocketworkstation.pckeyboard/databases doesn't exist
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:383)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
	at org.pocketworkstation.pckeyboard.AutoDictionary.query(AutoDictionary.java:212)
	at org.pocketworkstation.pckeyboard.AutoDictionary.loadDictionaryAsync(AutoDictionary.java:119)
	at org.pocketworkstation.pckeyboard.ExpandableDictionary$LoadDictionaryTask.doInBackground(ExpandableDictionary.java:498)
	at org.pocketworkstation.pckeyboard.ExpandableDictionary$LoadDictionaryTask.doInBackground(ExpandableDictionary.java:495)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
	... 20 more
	```

**Comment by jaceppo** [comment]
> 安装后我尝试设置其他语言，看起来保存设置发生了崩溃
> 
> ```
> FATAL EXCEPTION: AsyncTask #2
> Process: org.pocketworkstation.pckeyboard, PID: 17687
> java.lang.RuntimeException: An error occurred while executing doInBackground()
> 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
> 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
> 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
> 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:923)
> Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/mnt/expand/322a2c56-97f5-4a06-a139-ba607a4eb84d/user/0/org.pocketworkstation.pckeyboard/databases/auto_dict.db': Directory /mnt/expand/322a2c56-97f5-4a06-a139-ba607a4eb84d/user/0/org.pocketworkstation.pckeyboard/databases doesn't exist
> 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
> 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
> 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
> 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
> 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
> 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
> 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
> 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
> 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
> 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:383)
> 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
> 	at org.pocketworkstation.pckeyboard.AutoDictionary.query(AutoDictionary.java:212)
> 	at org.pocketworkstation.pckeyboard.AutoDictionary.loadDictionaryAsync(AutoDictionary.java:119)
> 	at org.pocketworkstation.pckeyboard.ExpandableDictionary$LoadDictionaryTask.doInBackground(ExpandableDictionary.java:498)
> 	at org.pocketworkstation.pckeyboard.ExpandableDictionary$LoadDictionaryTask.doInBackground(ExpandableDictionary.java:495)
> 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	... 4 more
> Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
> 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
> 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
> 	... 20 more
> 	```
> ```

**Comment by Krystianp00000** [comment]
https://github.com/klausw/hackerskeyboard/commit/080044b98167ad834854fdea739dea2fcbdb4f73
