### ISSUE TITLE
Unable to set as input method (continuous crashes)

### ISSUE THREAD

**Issue by 2011** [klausw/hackerskeyboard#940]
**Describe the bug**
Hacker's Keyboard crashes immediately (and repeatedly when attempting to select as input method).

**To Reproduce**
1. In either the Hacker's Keyboard application or Settings, attempt to set Hacker's Keyboard as the input method.
2. Hacker's Keyboard crashes immediately, and continues to crash as it keeps attempting to restart.

**Expected behavior**
I expect it to run. :)

**Smartphone (please complete the following information):**
 - Device: 905X3 television box
 - OS: Android 9 based custom ROM)
  - App version 1.41.1

**Additional context**
This worked find on the device until a relatively minor update to the ROM.

In the logs, this pretty much keeps repeating over and over (until I force stopped Hacker's Keyboard):

```
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=org.pocketworkstation.pckeyboard/.Main} from uid 10019

[03-04 23:53:38.535 3636:3654 I/ActivityManager]
Start proc 22046:org.pocketworkstation.pckeyboard/u0a81 for activity org.pocketworkstation.pckeyboard/.Main

[03-04 23:53:39.089 3409:4195 W/SurfaceFlinger]
Attempting to set client state on removed layer: thumbnail anim: AppWindowToken{a5ffe0f token=Token{d65a76e ActivityRecord{8c2aee9 u0 org.pocketworkstation.pckeyboard/.Main t348}}}#0

[03-04 23:53:39.089 3409:4195 W/SurfaceFlinger]
Attempting to destroy on removed layer: thumbnail anim: AppWindowToken{a5ffe0f token=Token{d65a76e ActivityRecord{8c2aee9 u0 org.pocketworkstation.pckeyboard/.Main t348}}}#0

[03-04 23:53:39.672 3636:3661 I/ActivityManager]
Displayed org.pocketworkstation.pckeyboard/.Main: +1s186ms

[03-04 23:53:46.158 22046:22046 I/PCKeyboard]
onCreate(), os.version=4.9.113

[03-04 23:53:46.218 22046:22046 I/PCKeyboard]
loaded jni_pckeyboard

[03-04 23:53:46.225 22046:22046 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: org.pocketworkstation.pckeyboard, PID: 22046
java.lang.RuntimeException: Unable to create service org.pocketworkstation.pckeyboard.LatinIME: java.lang.SecurityException: Failed to find provider user_dictionary for user 0; expected to find a valid ContentProvider for this authority
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Failed to find provider user_dictionary for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:779)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1972)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1961)
        at org.pocketworkstation.pckeyboard.UserDictionary.<init>(UserDictionary.java:50)
        at org.pocketworkstation.pckeyboard.LatinIME.initSuggest(LatinIME.java:617)
        at org.pocketworkstation.pckeyboard.LatinIME.onCreate(LatinIME.java:421)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.content.ContentService.registerContentObserver(Unknown Source:103)
        at android.content.IContentService$Stub.onTransact(IContentService.java:76)
        at com.android.server.content.ContentService.onTransact(Unknown Source:0)
        at android.os.Binder.execTransact(Binder.java:731)

[03-04 23:53:46.239 3636:9144 W/ActivityManager]
  Force finishing activity org.pocketworkstation.pckeyboard/.Main

[03-04 23:53:46.367 3636:3705 W/InputDispatcher]
channel '5d50585 org.pocketworkstation.pckeyboard/org.pocketworkstation.pckeyboard.Main (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[03-04 23:53:46.367 3636:3705 E/InputDispatcher]
channel '5d50585 org.pocketworkstation.pckeyboard/org.pocketworkstation.pckeyboard.Main (server)' ~ Channel is unrecoverably broken and will be disposed!

[03-04 23:53:46.375 3636:14820 I/WindowManager]
WIN DEATH: Window{5d50585 u0 org.pocketworkstation.pckeyboard/org.pocketworkstation.pckeyboard.Main}

[03-04 23:53:46.375 3636:14820 W/InputDispatcher]
Attempted to unregister already unregistered input channel '5d50585 org.pocketworkstation.pckeyboard/org.pocketworkstation.pckeyboard.Main (server)'

[03-04 23:53:46.376 3636:23632 I/ActivityManager]
Process org.pocketworkstation.pckeyboard (pid 22046) has died: fore TOP 

[03-04 23:53:46.376 3636:23632 W/ActivityManager]
Scheduling restart of crashed service org.pocketworkstation.pckeyboard/.LatinIME in 1000ms
```

Given the lack of maintenace on this project, I hope that someone can suggest a solution that does not involve installing a non-existient newer version. :)

**Comment by TPS** [comment]
Odds are, the next "relatively minor update to the ROM" is more likely to fix this than any HK update.
